import React from 'react'
import { Outlet, Link as RouterLink } from 'react-router-dom'
import AppBar from '@mui/material/AppBar'
import Toolbar from '@mui/material/Toolbar'
import IconButton from '@mui/material/IconButton'
import MenuIcon from '@mui/icons-material/Menu'
import Typography from '@mui/material/Typography'
import Box from '@mui/material/Box'
import Drawer from '@mui/material/Drawer'
import List from '@mui/material/List'
import ListItem from '@mui/material/ListItem'
import ListItemText from '@mui/material/ListItemText'
import Divider from '@mui/material/Divider'
export default function AppLayout(){const[open,setOpen]=React.useState(false);const items=[{text:'Dashboard',to:'/'},{text:'Agreements',to:'/agreements'},{text:'Payments',to:'/payments'},{text:'Reports',to:'/reports'}];return(<Box sx={{display:'flex'}}><AppBar position='fixed' color='primary' elevation={2}><Toolbar><IconButton edge='start' color='inherit' onClick={()=>setOpen(true)} sx={{mr:2}}><MenuIcon/></IconButton><Typography variant='h6' sx={{flexGrow:1}}>FlexFinance</Typography></Toolbar></AppBar><Drawer open={open} onClose={()=>setOpen(false)}><Box sx={{width:250}} role='presentation' onClick={()=>setOpen(false)}><Typography variant='h6' sx={{p:2}}>Menu</Typography><Divider/><List>{items.map(i=>(<ListItem button component={RouterLink} to={i.to} key={i.text}><ListItemText primary={i.text}/></ListItem>))}</List></Box></Drawer><Box component='main' sx={{flexGrow:1,p:3,mt:8}}><Outlet/></Box></Box>)}
