import React,{useEffect,useState}from'react'
import MockAPI from'../mockApi'
import Paper from'@mui/material/Paper'
import Typography from'@mui/material/Typography'
import Table from'@mui/material/Table'
import TableBody from'@mui/material/TableBody'
import TableCell from'@mui/material/TableCell'
import TableContainer from'@mui/material/TableContainer'
import TableHead from'@mui/material/TableHead'
import TableRow from'@mui/material/TableRow'
import Box from'@mui/material/Box'
import TextField from'@mui/material/TextField'
import Chip from'@mui/material/Chip'
export default function Agreements(){const[items,setItems]=useState([]);const[q,setQ]=useState('');useEffect(()=>{MockAPI.listAgreements().then(setItems)},[]);const filtered=items.filter(i=>!q||i.policyNumber.includes(q)||i.insured.toLowerCase().includes(q.toLowerCase()));const color=s=>s==='Active'?'success':(s==='Late'?'warning':'default');return(<><Typography variant='h4' gutterBottom>Agreements</Typography><Paper sx={{p:2,mb:2}}><Box sx={{display:'flex',gap:2,alignItems:'center',mb:2}}><TextField label='Search by policy or insured' value={q} onChange={e=>setQ(e.target.value)} sx={{flex:1}}/></Box><TableContainer><Table><TableHead><TableRow><TableCell>ID</TableCell><TableCell>Policy #</TableCell><TableCell>Insured</TableCell><TableCell>Premium</TableCell><TableCell>Status</TableCell><TableCell>Start</TableCell></TableRow></TableHead><TableBody>{filtered.map(r=>(<TableRow key={r.id} hover><TableCell>{r.id}</TableCell><TableCell>{r.policyNumber}</TableCell><TableCell>{r.insured}</TableCell><TableCell>${Number(r.premium).toLocaleString()}</TableCell><TableCell><Chip size='small' label={r.status} color={color(r.status)} variant={color(r.status)==='default'?'outlined':'filled'}/></TableCell><TableCell>{r.startDate}</TableCell></TableRow>))}</TableBody></Table></TableContainer></Paper></>) }
